name: flutterpassword
description: 高仿 1Password 桌面密码管理器应用
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI 相关
  cupertino_icons: ^1.0.6
  
  # 状态管理
  provider: ^6.1.1
  
  # 本地存储
  shared_preferences: ^2.2.2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # 加密
  crypto: ^3.0.3
  encrypt: ^5.0.3
  pointycastle: ^3.7.3
  
  # 图标
  flutter_svg: ^2.0.9
  
  # 工具类
  uuid: ^4.2.1
  intl: ^0.19.0
  
  # 文件操作
  file_picker: ^6.1.1
  path_provider: ^2.1.1
  
  # URL 启动
  url_launcher: ^6.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

